### ISSUE TITLE
Revision number integrated into code.

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/gens-rerecording#117]
On SVN, SubWCRev worked fine, but now (on Git) it outputs
`4>  SubWCRev : E155007: 'D:\SVN\Gens-rr-GitHub\gens-rerecording' is not a working copy`
There seem to be some manipulations with SubWCRev in TortoiseGit, but I never found anything that'd help me.

**Comment by marzojr** [comment]
Should be fixed.
